leftnav:
- identifier: 3b51fb2d-8b7a-48d1-aef8-6f1b4c450e2f
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 7de9420c-052a-4808-ae4d-5d8415f17d16
  name: Topics, Readings, Media
  pageRef: /pages/topics-readings-media
  weight: 20
- identifier: ef79c5a5-98e3-44b9-aa6c-20b18585e4e8
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
- identifier: 1a4ae8b0-f42c-4411-98c6-78fc30da6445
  name: Choice of Presentation
  pageRef: /pages/choice-of-presentation
  parent: ef79c5a5-98e3-44b9-aa6c-20b18585e4e8
  weight: 10
